rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1
  - ruby-head
before_script:
  - gem install minitest
  - sh bootstrap
  - ruby extconf.rb
  - make
script: rake
matrix:
  allow_failures:
    - rvm: ruby-head
